### PR TITLE
#121 Improve error handling

### LINKED ISSUE #121: Improve error handling
# Why

There should be a unified way to handle HTTP error responses for API calls and JavaScript runtime errors.

# What

* [x] **Runtime errors** should redirect the user to a standalone error page, because in some situations the Angular Application can not recover and you might have a broken UI. This code should follow some standard guidelines in order to support integration with 3rd party logging services like sentry.io
  * https://tools.ietf.org/html/rfc7231#section-6.5.1
  * https://www.php-fig.org/psr/psr-7/

* [x] **HTTP errors** should use the new error format defined in https://github.com/3angleTech/nodeApi/issues/28

* [x] **HTTP errors during router operations** should use a custom error handler that redirects the user to a new page depending on the type of error. 
  - "access denied" errors should display a login page for anonymous users or an info page for authenticated users.
  - other error pages should display an info page with an appropriate message. Error details should be hidden from the user.

* [x] **HTTP error for submitted forms** should have a way to display the error details to the user.

* [x] **All other HTTP errors** should use a generic error handler that hides the error details from the user, but the message should be configurable by the service.

### PR DESCRIPTION
**Pull request by SchnWalter**
Depends on 3angleTech/nodeApi#30

Fixes #121

### CODE REVIEW

File: web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts [hunk 1]
```diff
@@ -86,11 +96,10 @@ export class LoginPageComponent implements OnInit {
...
     this.loginForm.enable();
-    if (typeof err === 'object' && err['message']) {
-      alert('Login error!');
-      this.loginForm.setErrors({
-        submitError: err['message'],
-      });
+    if (err instanceof HttpErrorResponse) {
+      const validationErrors = getHttpResponseValidationErrors(err);
+      this.loginForm.setErrors(validationErrors);
+      this.loginForm.markAsUntouched();
```
Comment (SchnWalter) [inline web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts:102]: With these changes the forms have a very nice UX and I think that I have figured out a way to extract the feature into a directive so that it's reusable on all pages and the form container (the login page in this case) will need to implement a simple interface and the directive will be added directly to the form element.

```

export interface IAppFormContainer<S = void> {
  readonly I18N_NAMESPACE: string;

  getSubmitObservable(formGroup: FormGroup): Observable<S>;
}
```

File: web-frame/src/app-shared/core/errors/get-http-response-validation-errors.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  if (response.status === HttpStatusCode.CONNECTION_REFUSED) {
+    return {
+      'GENERAL.ERROR.CONNECTION_REFUSED': true,
+    };
+  }
+
+  // TODO: Add support for more multiple translations.
+  if (isApiError(response.error)) {
+    return {
+      [response.error.name]: true,
```
Comment (SchnWalter) [inline web-frame/src/app-shared/core/errors/get-http-response-validation-errors.ts:23]: I've added this TODO here in case we want to add more complex error responses. Currently, we only support a single translatable error message.

File: web-frame/src/app/app-routing-error-handler.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+import { AccessDeniedError, HttpStatusCode, PAGE_URL, PageNotFoundError, WebFrameErrorHandlerService } from '~app-shared/core';
+
+export function appRoutingErrorHandler(this: Router, err: unknown): unknown {
+  const extras: NavigationExtras = { skipLocationChange: true };
+  if (err instanceof AccessDeniedError) {
+    return this.navigateByUrl(PAGE_URL.ACCESS_DENIED_PAGE, extras);
+  } else if (err instanceof PageNotFoundError) {
+    return this.navigateByUrl(PAGE_URL.PAGE_NOT_FOUND_PAGE, extras);
+  } else if (err instanceof HttpErrorResponse) {
+    if (err.status === HttpStatusCode.FORBIDDEN) {
```
Comment (cadobre) [inline web-frame/src/app/app-routing-error-handler.ts:19]: This function is hard for the eyes to read, I would extract the block of code for HttpErrorReponse into a function HttpErrorResponseHandler. This way we can also reduce the nesting level by 1

File: web-frame/src/app/app-routing-error-handler.ts [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+      return this.navigateByUrl(PAGE_URL.ACCESS_DENIED_PAGE, extras);
+    } else if (err.status >= HttpStatusCode.BAD_REQUEST
+      && err.status < HttpStatusCode.INTERNAL_SERVER_ERROR) {
+      return this.navigateByUrl(PAGE_URL.PAGE_NOT_FOUND_PAGE, extras);
+    } else if (err.status >= HttpStatusCode.INTERNAL_SERVER_ERROR) {
+      try {
+        const errorString: string = JSON.stringify(err);
+        window.sessionStorage.setItem(WebFrameErrorHandlerService.LAST_RUNTIME_ERROR_KEY, errorString);
```
Comment (cadobre) [inline web-frame/src/app/app-routing-error-handler.ts:27]: This is like a magic key that you need to know it's stored from this location.
Why not create a method on WebFrameErrorHandlerService that implements these details behind the scene, so everything is unified under the same service.

```typescript
try {
   WebFrameErrorHandlerService.updateLastRuntimeError(error)
}

```

File: web-frame/src/app/app-routing-error-handler.ts [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+      } catch (err) {
+        // Ignore storageArea issues and just display a generic error page.
+        console.error('Failed to serialize the navigation error object for the error page.');
+      }
+      window.location.href = ENVIRONMENT.appBaseUrl + trimStart(PAGE_URL.STANDALONE_ERROR_PAGE, '/');
```
Comment (cadobre) [inline web-frame/src/app/app-routing-error-handler.ts:32]: why do we use the trimStart ? We could just update PAGE_URL enums to remove the '/' prefix.

File: web-frame/src/app/app.module.ts [hunk 6]
```diff
@@ -28,6 +29,14 @@ import { AppComponent } from './app.component';
     CoreModule.forRoot(),
     SecurityModule.forRoot(),
   ],
+  providers: [
+    APP_ERROR_HANDLER_PROVIDER,
```
Comment (cadobre) [inline web-frame/src/app/app.module.ts:33]: I am having a hard time to follow what is the convention for naming here, if we should use upper case or camelcase. Why did you decide to make it upper case?

File: web-frame/src/assets/i18n/en.json [hunk 7]
```diff
@@ -57,13 +71,20 @@
       "SUBMIT": "Login",
       "CREATE_ACCOUNT": "Create account",
       "FORGOT_PASSWORD": "Forgot password?",
-      "ERRORS": {
+      "ERROR": {
+        "EMAIL": {
+          "email": "Email is invalid.",
```
Comment (cadobre) [inline web-frame/src/assets/i18n/en.json:76]: Update to uppercase

File: web-frame-error/index.html [hunk 8]
```diff
@@ -42,35 +48,40 @@ <h1>Runtime Error!</h1>
      * @return { Error | undefined }
      */
     function getErrorInfo() {
-      const errorInfoString = /** @type { string } */
-        window.sessionStorage.getItem(LAST_RUNTIME_ERROR_KEY);
+      /** @type { Partial<Error> | unknown } */
+      let errorDetails;
+      try {
+        const errorInfoString = /** @type { string } */
+          window.sessionStorage.getItem(LAST_RUNTIME_ERROR_KEY);
```
Comment (cadobre) [inline web-frame-error/index.html:55]: identation

File: web-frame-error/index.html [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+    /** @type { {errorInfo: Partial<Error>} } */
+    const ERROR_PAGE_DATA = {};
+    ERROR_PAGE_DATA.errorInfo = getErrorInfo();
+
+    const detailsContainerEl = /** @type { HTMLDivElement } */
+      document.getElementById('error-details');
+
+    if (ERROR_PAGE_DATA.errorInfo) {
+      const errorNameEl = /** @type { HTMLHeadingElement } */
+        document.createElement('h2');
```
Comment (cadobre) [inline web-frame-error/index.html:93]: add proper identation for all

File: web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts [hunk 10]
```diff
@@ -79,13 +67,40 @@ export class LoginPageComponent implements OnInit {
...
+    if (this.loginForm.invalid || this.loginForm.errors) {
+      this.showFormGroupErrorsNotification();
+
+      return false;
+    }
+
+    return true;
+  }
+
+  private hasConnectionRefusedError(errors: ValidationErrors): boolean {
```
Comment (cadobre) [inline web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts:91]: isConnectionRefusedError

File: web-frame/src/app-shared/core/initializers/app-state-initializer.service.ts [hunk 11]
```diff
@@ -36,6 +36,10 @@ export class AppStateInitializerService {
   private logoutAndReloadApplication(): Observable<never> {
     return this.accountService.logout().pipe(
       mergeMap((): Observable<never> => {
+        // TODO: Fix possible race condition and use translated messages.
```
Comment (cadobre) [inline web-frame/src/app-shared/core/initializers/app-state-initializer.service.ts:39]: Create follow up task and update TODO with the id.

File: web-frame/src/app-feature/account-feature/pages/information-page/information-page.component.html [hunk 12]
```diff
@@ -10,10 +10,19 @@ <h1 class="app-page__title">{{ getPageTitle() | translate }}</h1>
...
-      </span>
-    </button>
+    <ng-container *ngIf="isAuthenticated; else anonymousAction">
+      <button class="app-button--with-icon" type="button" (click)="navigateToDestinationPage()">
+        <span class="text">
+          {{ 'GENERAL.BUTTON.GO_BACK' | translate }}
+        </span>
+      </button>
+    </ng-container>
+    <ng-template #anonymousAction>
```
Comment (cadobre) [inline web-frame/src/app-feature/account-feature/pages/information-page/information-page.component.html:20]: minor: Maybe we could rename to "annonymousUserActions"? I did not get what it was the intent from the first read.

File: web-frame/src/app/app-routing-error-handler.ts (hunk 4 above)
Comment (SchnWalter) [reply web-frame/src/app/app-routing-error-handler.ts]: * created 3 helper functions: `isAccessDeniedError`, `isPageNotFoundError` and `isInternalServerError`.
* Replaced the "go to error page" logic with a call to this static method: `WebFrameErrorHandlerService.DISPLAY_STANDALONE_ERROR_PAGE()`

File: web-frame/src/app/app-routing-error-handler.ts (hunk 5 above)
Comment (SchnWalter) [reply web-frame/src/app/app-routing-error-handler.ts]: It's a bit more complicated. I've removed this concatenation and added a followup story #143

File: web-frame/src/app/app.module.ts (hunk 6 above)
Comment (SchnWalter) [reply web-frame/src/app/app.module.ts:33]: We use SNAKE_CASE for all constants and this constant references a `Provider` that provides a custom error handler. And I kept that provider next to the actual error handler to having many imports in the `app.module.ts`.

File: web-frame/src/assets/i18n/en.json (hunk 7 above)
Comment (SchnWalter) [reply web-frame/src/assets/i18n/en.json:76]: We can't really do this. These are translation tokens contain values from `ValidationErrors` instances and we don't control those. We could use a `snakeCase` function, but then it would make searching for these errors a bit hard. I would keep this as an exception, at least for now.

File: web-frame-error/index.html [hunk 13]
```diff
@@ -0,0 +1,112 @@
...
+
+    /**
+     * @return { Error | undefined }
+     */
+    function getErrorInfo() {
+      /** @type { Partial<Error> | unknown } */
+      let errorDetails;
+      try {
+        const errorInfoString = /** @type { string } */
+          window.sessionStorage.getItem(LAST_RUNTIME_ERROR_KEY);
```
[the remark this answers is not in the document]
Comment (SchnWalter) [reply web-frame-error/index.html]: I've moved the type annotation to a separate line for all these JSDoc instances.
```
        /** @type { string } */
        const errorInfoString = window.sessionStorage.getItem(LAST_RUNTIME_ERROR_KEY);
```

File: web-frame-error/index.html (hunk 9 above)
Comment (SchnWalter) [reply web-frame-error/index.html]: Fixed. See https://github.com/3angleTech/webFrame/pull/140#discussion_r439670762

File: web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts (hunk 10 above)
Comment (SchnWalter) [reply web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts]: Done

File: web-frame/src/app-shared/core/initializers/app-state-initializer.service.ts (hunk 11 above)
Comment (SchnWalter) [reply web-frame/src/app-shared/core/initializers/app-state-initializer.service.ts]: Actually, I just realized that the final version didn't have a race condition so I've update the code to use the translation system.

File: web-frame/src/app-feature/account-feature/pages/information-page/information-page.component.html (hunk 12 above)
Comment (SchnWalter) [reply web-frame/src/app-feature/account-feature/pages/information-page/information-page.component.html]: Done

File: web-frame/src/app/app-routing-error-handler.ts (hunk 3 above)
Comment (SchnWalter) [reply web-frame/src/app/app-routing-error-handler.ts:22]: Fixed: https://github.com/3angleTech/webFrame/pull/140#discussion_r439669337

File: web-frame-error/index.html [hunk 14]
```diff
@@ -0,0 +1,112 @@
...
+<head>
+  <meta charset="UTF-8">
+  <meta content="width=device-width, initial-scale=1.0" name="viewport">
+  <meta content="ie=edge" http-equiv="X-UA-Compatible">
+  <title> Runtime Error!</title>
+  <base href="/">
+  <style>
+    body {
+      display: grid;
+      font-family: "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", system-ui, sans-serif;
```
Comment (SchnWalter) [inline web-frame-error/index.html:17]: FYI: This font stack includes the native fonts for most operating systems.

Inspired from: https://design-system.protontech.ch/typography/

File: web-frame/src/app/app-routing-error-handler.ts (hunk 4 above)
Comment (cadobre) [reply web-frame/src/app/app-routing-error-handler.ts]: Sorry I cannot see how the response is related to what I wrote. Maybe you wanted to reply to a different comment

Comment (SchnWalter) [reply web-frame/src/app/app-routing-error-handler.ts]: The call to SessionStorage was only needed because the routing error handler was also performing the redirect to the error page.


I have now converted all relevant methods to static and instead of using the `LAST_RUNTIME_ERROR_KEY` static property, the sessions storage call is performed by a `DISPLAY_STANDALONE_ERROR_PAGE()` static method call. Now there is no need to create a `updateLastRuntimeError()` method, it's now a hidden implementation detail.

File: web-frame/src/app-shared/core/errors/get-http-response-validation-errors.ts (hunk 2 above)
Comment (SchnWalter) [reply web-frame/src/app-shared/core/errors/get-http-response-validation-errors.ts:22]: Removed the todo and created #144

File: web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts (hunk 1 above)
Comment (SchnWalter) [reply web-frame/src/app-feature/account-feature/pages/login-page/login-page.component.ts:121]: Created #145

File: web-frame/src/app-feature/sandbox-feature/components/sandbox-list/sandbox-list.component.html [hunk 15]
```diff
@@ -0,0 +1,17 @@
+<ng-container *ngIf="list.items && list.items.length">
```
[the remark this answers is not in the document]
Comment (SchnWalter) [reply web-frame/src/app-feature/sandbox-feature/components/sandbox-list/sandbox-list.component.html]: Fixed

File: web-frame/src/app-shared/core/components/form-group-errors/form-group-errors.component.spec.ts [hunk 16]
```diff
@@ -0,0 +1,29 @@
+/**
```
[the remark this answers is not in the document]
Comment (SchnWalter) [reply web-frame/src/app-shared/core/components/form-group-errors/form-group-errors.component.spec.ts:1]: Done
